packages:
  - "apps/*"
  - "packages/*"
  - "packages/*/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true

onlyBuiltDependencies:
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
